### ISSUE TITLE
typo in decode.decode

### ISSUE THREAD

**Issue by adalke** [baoilleach/deepsmiles#4]
The decode method for the default Converter gives an error:
```
>>> deepsmiles.Converter().decode("C")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "deepsmiles/converter.py", line 41, in decode
    return decode.decode(deepsmiles, rings=self.rings, branches=self.branches)
  File "deepsmiles/decode.py", line 242, in decode
    return smi
NameError: name 'smi' is not defined
```
This is because of a typo in decode.py:decode():
```
def decode(deepsmiles, rings=False, branches=False):
    ....
    if not rings and not branches:
        return smi
```
That last quoted line should be `return deepsmiles`.

**Comment by baoilleach** [comment]
Doh. Will do.

**Comment by baoilleach** [comment]
Done.
